"""Write the SAP2000 text import file (.$2k) of the Muelle de Trasmallo model.

    python tools/write_s2k.py [-o output/Muelle_Trasmallo_40m.$2k]

In SAP2000:  File > Import > SAP2000 .s2k/.$2k/.xlsx/.mdb/.xml...  select the file, then
Analyze > Run Analysis (F5).  Units of the file: kN, m, C.
"""

from __future__ import annotations

import argparse
import sys
import unicodedata
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / "model"))

import trasmallo as tm  # noqa: E402

SAP_VERSION = "22.0.0"


def ascii_text(s: str) -> str:
    """SAP2000 reads the text file as ANSI: keep it pure ASCII (drop accents)."""
    return unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")


def fmt(v) -> str:
    """Format one value the way SAP2000 writes it (quotes around values with spaces)."""
    if isinstance(v, bool):
        return "Yes" if v else "No"
    if isinstance(v, float):
        if v == 0:
            return "0"
        s = f"{v:.10G}"
        return s.replace("E+", "E+").replace("E-0", "E-0")
    s = ascii_text(str(v)).replace('"', "'")
    if any(c in s for c in " ,") or s == "":
        return f'"{s}"'
    return s


class S2K:
    def __init__(self) -> None:
        self.lines: list[str] = []

    def table(self, title: str, rows: list[dict]) -> None:
        if not rows:
            return
        self.lines.append(f'TABLE:  "{title}"')
        for row in rows:
            self.lines.append("   " + "   ".join(f"{k}={fmt(v)}" for k, v in row.items()))
        self.lines.append("")

    def text(self) -> str:
        return "\n".join(self.lines + ["END TABLE DATA", ""])


def build_tables(model: dict) -> S2K:
    s = S2K()
    s.lines += [f"File Muelle_Trasmallo_40m.$2k - generated by tools/write_s2k.py "
                "(Anejo 10, Cullera - Muelle de Trasmallo, modulo de 40 m)", ""]

    s.table("PROGRAM CONTROL", [{
        "ProgramName": "SAP2000", "Version": SAP_VERSION, "ProgLevel": "Ultimate",
        "CurrUnits": "KN, m, C", "SteelCode": "Eurocode 3-2005",
        "ConcCode": "Eurocode 2-2004", "RegenHinge": True}])
    s.table("ACTIVE DEGREES OF FREEDOM", [{
        "UX": True, "UY": True, "UZ": True, "RX": True, "RY": True, "RZ": True}])
    s.table("ANALYSIS OPTIONS", [{"Solver": "Advanced", "SolverProc": "Auto"}])
    s.table("COORDINATE SYSTEMS", [{
        "Name": "GLOBAL", "Type": "Cartesian", "X": 0.0, "Y": 0.0, "Z": 0.0,
        "AboutZ": 0.0, "AboutY": 0.0, "AboutX": 0.0}])

    # ---- materials ---------------------------------------------------------------------------
    s.table("MATERIAL PROPERTIES 01 - GENERAL", [
        {"Material": m.name, "Type": m.kind, "SymType": "Isotropic", "TempDepend": False,
         "Color": "Gray8Dark" if m.kind == "Concrete" else "Red", "Notes": m.note}
        for m in model["materials"]])
    s.table("MATERIAL PROPERTIES 02 - BASIC MECHANICAL PROPERTIES", [
        {"Material": m.name, "UnitWeight": m.unit_weight, "UnitMass": m.unit_weight / 9.80665,
         "E1": m.E, "G12": m.E / (2 * (1 + m.nu)), "U12": m.nu, "A1": m.alpha}
        for m in model["materials"]])
    s.table("MATERIAL PROPERTIES 03b - CONCRETE DATA", [
        {"Material": m.name, "Fc": m.fc, "LtWtConc": False, "SSCurveOpt": "Mander",
         "SSHysType": "Takeda", "SFc": 0.002, "SCap": 0.0035, "FinalSlope": -0.1,
         "FAngle": 0.0, "DAngle": 0.0}
        for m in model["materials"] if m.kind == "Concrete"])
    s.table("MATERIAL PROPERTIES 03e - REBAR DATA", [
        {"Material": m.name, "Fy": m.fy, "Fu": m.fu, "EffFy": m.fy, "EffFu": m.fu,
         "SSCurveOpt": "Simple", "SSHysType": "Kinematic", "SHard": 0.01, "SCap": 0.09,
         "FinalSlope": -0.1, "UseCTDef": False}
        for m in model["materials"] if m.kind == "Rebar"])

    # ---- frame sections ------------------------------------------------------------------------
    rows = []
    for fs in model["sections"].values():
        p = fs.section.props
        mod = {"AMod": 1.0, "A2Mod": 1.0, "A3Mod": 1.0, "JMod": 1.0, "I2Mod": 1.0,
               "I3Mod": 1.0, "MMod": 1.0, "WMod": 1.0}
        mod.update(fs.modifiers)
        row = {"SectionName": fs.name, "Material": fs.material, "Shape": fs.shape,
               "t3": p["t3"], "t2": p["t2"]}
        if fs.shape == "General":
            row.update({k: p[k] for k in ("Area", "TorsConst", "I33", "I22", "AS2",
                                          "AS3", "S33", "S22", "Z33", "Z22", "R33", "R22")})
            row["I23"] = 0.0     # frame elements work in principal axes (L-shape I23 neglected)
        row.update({"Color": "Cyan" if fs.name.startswith("PIL") else "Green",
                    "Notes": fs.section.description})
        row.update(mod)
        rows.append(row)
    s.table("FRAME SECTION PROPERTIES 01 - GENERAL", rows)

    slab = model["slab"]
    s.table("AREA SECTION PROPERTIES", [{
        "Section": slab["name"], "Material": slab["material"], "MatAngle": 0.0,
        "AreaType": "Shell", "Type": "Shell-Thin", "DrillDOF": True,
        "Thickness": slab["thickness"], "BendThick": slab["thickness"], "Arc": 0.0,
        "InComp": True, "CoordSys": "GLOBAL", "Color": "Yellow",
        "F11Mod": 1.0, "F22Mod": 1.0, "F12Mod": 1.0,
        "M11Mod": round(slab["m11"], 6), "M22Mod": slab["m22"], "M12Mod": slab["m12"],
        "V13Mod": 1.0, "V23Mod": 1.0, "MMod": slab["mass_mod"], "WMod": slab["weight_mod"],
        "Notes": "PRENOR P-25+5/120: EI = 63550 kN m2/m along local 1 (= X), one-way"}])

    # ---- geometry ------------------------------------------------------------------------------
    s.table("JOINT COORDINATES", [
        {"Joint": j, "CoordSys": "GLOBAL", "CoordType": "Cartesian", "XorR": x, "Y": y, "Z": z,
         "SpecialJt": False, "GlobalX": x, "GlobalY": y, "GlobalZ": z}
        for j, (x, y, z) in model["joints"].items()])
    s.table("CONNECTIVITY - FRAME", [
        {"Frame": f["name"], "JointI": f["i"], "JointJ": f["j"], "IsCurved": False}
        for f in model["frames"]])
    s.table("CONNECTIVITY - AREA", [
        {"Area": a["name"], "NumJoints": 4, "Joint1": a["joints"][0], "Joint2": a["joints"][1],
         "Joint3": a["joints"][2], "Joint4": a["joints"][3]}
        for a in model["areas"]])

    s.table("JOINT RESTRAINT ASSIGNMENTS", [
        {"Joint": j, "U1": r[0], "U2": r[1], "U3": r[2], "R1": r[3], "R2": r[4], "R3": r[5]}
        for j, r in model["restraints"].items()])
    d = model["diaphragm"]
    s.table("CONSTRAINT DEFINITIONS - DIAPHRAGM", [
        {"Name": d["name"], "CoordSys": "GLOBAL", "Axis": "Z", "MultiLevel": False}])
    s.table("JOINT CONSTRAINT ASSIGNMENTS", [
        {"Joint": j, "Constraint": d["name"], "Type": "Diaphragm"} for j in d["joints"]])

    s.table("FRAME SECTION ASSIGNMENTS", [
        {"Frame": f["name"], "AutoSelect": "N.A.", "AnalSect": f["section"],
         "DesignSect": f["section"], "MatProp": "Default"}
        for f in model["frames"]])
    s.table("FRAME LOCAL AXES ASSIGNMENTS 1 - TYPICAL", [
        {"Frame": f["name"], "Angle": f["angle"], "AdvanceAxes": False}
        for f in model["frames"] if f.get("angle")])
    s.table("FRAME OUTPUT STATION ASSIGNMENTS", [
        {"Frame": f["name"], "StationType": "MaxSpace", "MaxStaSpcg": f["station_max"],
         "AddAtElmInt": True, "AddAtPtLoad": True}
        for f in model["frames"]])
    s.table("FRAME OFFSET ALONG LENGTH ASSIGNMENTS", [
        {"Frame": f["name"], "LengthOpt": "User Defined", "LengthI": f["offsets"][0],
         "LengthJ": f["offsets"][1], "RigidFact": 1.0}
        for f in model["frames"] if f.get("offsets") and any(f["offsets"])])
    s.table("AREA SECTION ASSIGNMENTS", [
        {"Area": a["name"], "Section": a["section"], "MatProp": "Default"}
        for a in model["areas"]])

    # ---- groups --------------------------------------------------------------------------------
    s.table("GROUPS 1 - DEFINITIONS", [
        {"GroupName": g, "Selection": True, "SectionCut": True, "Steel": True, "Concrete": True,
         "Aluminum": True, "ColdFormed": True, "Stage": True, "Bridge": True,
         "AutoSeismic": False, "AutoWind": False, "SelDesSteel": False, "SelDesAlum": False,
         "SelDesCold": False, "MassWeight": True, "Color": "Blue"}
        for g in model["groups"]])
    s.table("GROUPS 2 - ASSIGNMENTS", [
        {"GroupName": g, "ObjectType": kind, "ObjectLabel": name}
        for g, objs in model["groups"].items() for kind, name in objs])

    # ---- load patterns, cases, combinations --------------------------------------------------
    s.table("LOAD PATTERN DEFINITIONS", [
        {"LoadPat": n, "DesignType": dt, "SelfWtMult": sw, "Notes": note}
        for n, dt, sw, note in tm.LOAD_PATTERNS])
    s.table("LOAD CASE DEFINITIONS", [
        {"Case": n, "Type": "LinStatic", "InitialCond": "Zero", "DesTypeOpt": "Prog Det",
         "DesignType": dt, "RunCase": True}
        for n, dt, _, _ in tm.LOAD_PATTERNS])
    s.table("CASE - STATIC 1 - LOAD ASSIGNMENTS", [
        {"Case": n, "LoadType": "Load pattern", "LoadName": n, "LoadSF": 1.0}
        for n, *_ in tm.LOAD_PATTERNS])

    rows = []
    for fam, combos in tm.COMBOS.items():
        design = "Strength" if fam != "ELS" else "None"
        for k, fac in enumerate(combos, start=1):
            cname = f"{fam}{k:02d}"
            first = True
            for pat, sf in zip(tm.PATTERN_ORDER, fac):
                if sf == 0:
                    continue
                row = {"ComboName": cname}
                if first:
                    row.update({"ComboType": "Linear Add", "AutoDesign": False})
                row.update({"CaseType": "Linear Static", "CaseName": pat, "ScaleFactor": float(sf)})
                if first:
                    row.update({"SteelDesign": "None", "ConcDesign": design,
                                "AlumDesign": "None", "ColdDesign": "None"})
                    first = False
                rows.append(row)
        # envelope of the family
        env = f"ENV_{fam}"
        for k in range(1, len(combos) + 1):
            row = {"ComboName": env}
            if k == 1:
                row.update({"ComboType": "Envelope", "AutoDesign": False})
            row.update({"CaseType": "Response Combo", "CaseName": f"{fam}{k:02d}", "ScaleFactor": 1.0})
            if k == 1:
                row.update({"SteelDesign": "None", "ConcDesign": "None", "AlumDesign": "None",
                            "ColdDesign": "None"})
            rows.append(row)
    s.table("COMBINATION DEFINITIONS", rows)

    # ---- loads ---------------------------------------------------------------------------------
    s.table("JOINT LOADS - FORCE", [
        {"Joint": jl["joint"], "LoadPat": jl["pattern"], "CoordSys": "GLOBAL",
         "F1": jl["F"][0], "F2": jl["F"][1], "F3": jl["F"][2],
         "M1": jl["F"][3], "M2": jl["F"][4], "M3": jl["F"][5]}
        for jl in model["joint_loads"]])
    s.table("FRAME LOADS - DISTRIBUTED", [
        {"Frame": fl["frame"], "LoadPat": fl["pattern"], "CoordSys": "GLOBAL", "Type": "Force",
         "Dir": "Gravity", "DistType": "RelDist", "RelDistA": 0.0, "RelDistB": 1.0,
         "FOverLA": fl["w"], "FOverLB": fl["w"]}
        for fl in model["frame_loads"]])
    s.table("AREA LOADS - UNIFORM", [
        {"Area": al["area"], "LoadPat": al["pattern"], "CoordSys": "GLOBAL", "Dir": "Gravity",
         "UnifLoad": al["q"]}
        for al in model["area_loads"]])
    return s


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out", type=Path, default=ROOT / "output" / "Muelle_Trasmallo_40m.$2k")
    args = ap.parse_args()
    model = tm.build_model()
    s = build_tables(model)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(s.text(), encoding="utf-8")
    print(f"written {args.out}  ({len(s.lines)} lines)")


if __name__ == "__main__":
    main()
